### PR TITLE
2D surface processes implementation

### PR DESCRIPTION
**Pull request by bknight1**
Implementation of surface processes in 2D. (1) erosion and sedimentation rate (2) diffusive surface.

Updated tutorial list with 6.1 (erosion and sedimentation rate) and 6.2 (diffusive surface).

Updated user guide with info on how to include these processes in models.

### CODE REVIEW

**Comment by julesghub** [comment]
Nice work @bknight1. We'll review this week and get back to you.

**Comment by rbeucher** [comment]
Great! I'm gonna look at that.
Thanks @bknight1 !

**Comment by bknight1** [comment]
Thanks @julesghub and @rbeucher 

I realised I pulled the tutorials from v2.10.2, so the Model.init_model will need updating.

I have also just noticed that the way to include passive tracers has changed so I'll have to update some parts of the code in the surface processes file. What's the best way to make these changes?

**Comment by bknight1** [comment]
I've updated the passive tracers to be accessed through Model, however when trying to update the z coordinates I get the following error: ValueError: assignment destination is read-only

Example to recreate error:

```
import numpy as np

npoints = int(Model.length.magnitude)


coords = np.ndarray((npoints, 2))
coords[:, 0] = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
coords[:, 1] = GEO.nd(uppercrust.top)
Model.add_passive_tracers(name="PT", vertices=coords, advect=False)
Model.PT_tracers.data[:,0] = 0.
```


Using:
UW version - 2.11.0b
UWGeodynamics version - 2.11.0-dev-485ad28(master)

**Comment by rbeucher** [comment]
@NengLu can you have a look at this please?

**Comment by NengLu** [comment]
> @NengLu can you have a look at this please?

Sure, 
by the way, thanks ben for sharing this.

**Comment by NengLu** [comment]
> ValueError: assignment destination is read-only

Hi, Ben, the PT_tracer should be set like:
```
Model.PT_tracers = Model.add_passive_tracers(name="PT", vertices=coords, advect=False)
Model.PT_tracers.data[:,0] = 0.
```
or independently, not the Model's attribute, like:
```
PT_tracers = Model.add_passive_tracers(name="PT", vertices=coords, advect=False)
PT_tracers.data[:,0] = 0.
```
And here PT_tracer.data[:,0] is initially set by "add_passive _tracters" be coords[:, 0], then be set to 0.
If you want to tracer another field, it could be done like:
```
PT_tracers.add_tracked_field(Model.velocityField,
                              name="tracers_vel",
                              units=u.meter/u.year,
                              dataType="float")
```

**Comment by rbeucher** [comment]
No Neng. The passive tracers access method has been updated. You can't do that anymore. @julesghub why do we get a read only error?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rbeucher** [comment]
Tracers are swarms. So to access the coordinates you need to use:

`Model.PT_tracers.particleCoordinates.data[:, 0] = 0.`

**Comment by bknight1** [comment]
I have just tried that and getting the same error @rbeucher 

'ValueError: assignment destination is read-only'

**Comment by julesghub** [comment]
I believe the read only error is because the swarm is under a context manager, ie. one needs to use the following to `write` values to the data structure.
```python
with Model.PT_tracers.deform_swarm():
   Model.PT_tracers.particleCoordinates.data[:,0] = 0.
```

**Comment by bknight1** [comment]
Thanks @julesghub that works! Will re-run the tests and update the files today

**Comment by rbeucher** [comment]
Great @NengLu will go through your examples and then we can merge.

**Comment by bknight1** [comment]
Should be good to go now @NengLu

**Comment by NengLu** [comment]
> Should be good to go now @NengLu

Hi, Romain and Ben @rbeucher @bknight1,
I have gone through the codes and examples, there are small typos in the Tutorial_6.1 and Tutorial_6.2,
`Model.surfacetracers_tracers `should be `Model.surface_tracers`

The topography from sedimentation&erosion seems incorrect, may need a further check with `velocitySurface_2D(SurfaceProcesses)`
Topo

**Comment by rbeucher** [comment]
What's the reference for the elevations?

**Comment by bknight1** [comment]
I believe this is due to differences in the diffusivity rate (D = 150 m2/yr) and erosion and sedimentation rates (2 mm/yr). That's my fault for leaving in a very high erosion and sedimentation rate, which would flatten the topography very quickly (as is seen in the figure for elevation).

A more appropriate erosion and sedimentation rate should be ~0.15 mm/yr, which should then produce a similar topography to the no erosion and diffusive surface models.

```
Model.surfaceProcesses = velocitySurface(
    airIndex=air.index,
    sedimentIndex=sediment.index,
    sedimentationRate= 0.15*u.millimeter / u.year,
    erosionRate= 0.15*u.millimeter / u.year,
    surfaceElevation=uppercrust.top,
    surfaceArray = coords,
    updateSurfaceLB=5.*u.kilometer, updateSurfaceRB=5.*u.kilometer
)
```

**Comment by NengLu** [comment]
> I believe this is due to differences in the diffusivity rate (D = 150 m2/yr) and erosion and sedimentation rates (2 mm/yr). That's my fault for leaving in a very high erosion and sedimentation rate, which would flatten the topography very quickly (as is seen in the figure for elevation).
> 
> A more appropriate erosion and sedimentation rate should be ~0.15 mm/yr, which should then produce a similar topography to the no erosion and diffusive surface models.
> 
> ```
> Model.surfaceProcesses = velocitySurface_2D(
>     airIndex=air.index,
>     sedimentIndex=sediment.index,
>     sedimentationRate= 0.15*u.millimeter / u.year,
>     erosionRate= 0.15*u.millimeter / u.year,
>     surfaceElevation=uppercrust.top,
>     surfaceArray = coords
> )
> ```
> 
> @rbeucher the reference height for the erosion & sedimentation rate is 0 km (uppercrust.top), which is why the topography is flattened out at 0 km except for the parts that experience the most uplift (at around x = 120 km and x = 240 km).

Merge is good to go! @rbeucher 
Topo

**Comment by rbeucher** [comment]
Awesome guys. Thanks @bknight1 @NengLu

**Comment by bknight1** [comment]
Nice one, thanks everyone!

**Comment by rbeucher** [comment]
@bknight1 can you send me your ORCID so I can add you to the list of contributors?

**Comment by bknight1** [comment]
It's 0000-0001-7919-2575, thanks @rbeucher

**Pull request merged**
