### PR TITLE
Passive Tracers can now track swarm fields…

### PR DESCRIPTION
**Pull request by rbeucher**
This should allow tracking material indices among other things.
This is to address some of the issues that Benedicte is facing in her models.

### CODE REVIEW

**Comment by julesghub** [comment]
Very cool!

**Comment by BenedicteCT** [comment]
Thanks. Tried running a script adding .materialField to passive tracers with 2.10pre-release on docker and get this error message:
'ParticleCoordinate' input and `SwarmVariableFn` function appear to be based on different swarms.

**Comment by rbeucher** [comment]
Yes. It won't be available before the official release. The version you have in the docker you mentioned is probably still 2.9.6. Try to do `GEO.__version__`

**Comment by rbeucher** [comment]
@julian We need to make the Dockerfile aware of the branch it is in... Maybe do a COPY instead of a `pip install`

**Comment by BenedicteCT** [comment]
It seems that there is a 2.10pre-release on docker but correct running GEO.__version__ yields 2.9.5

**Comment by rbeucher** [comment]
@julian I have made some changes. Yes @benedicte.. I wasn't expecting you to try it!! hahahah my bad!

**Comment by BenedicteCT** [comment]
Tried this morning right after the release but kept a little time to search on my own before posting...

**Comment by rbeucher** [comment]
I'll let you know when it's ready. Should not be long

**Comment by julesghub** [comment]
Yeah, the 

> @Julian We need to make the Dockerfile aware of the branch it is in... Maybe do a COPY instead of a `pip install`

Or we do a pip3 install from the github on the correct branch name? I believe that's possible

**Comment by rbeucher** [comment]
I dont think you can reference the current branch... We could pass the branch name to the dockerfile as argument...

**Comment by rbeucher** [comment]
@BenedicteCT  Have a go at the "benedicte" docker. It's essentially 2.10... which we haven't released yet.

R

**Comment by BenedicteCT** [comment]
Have you changed the way to define coordinates for passive tracers in general ?
Error when I define coord for interface tracers: "TypeError: 'coordinateArray' must be provided as a numpy array"
Error when I define min max coord for FSE_crust: "ValueError: too many values to unpack (expected 2)"
Error when I define passive tracers grid "TypeError: list indices must be integers or slices, not tuple"

All these are defined as "Model.add_passive_tracers"+ coordinates

**Comment by rbeucher** [comment]
Yes I have. I was getting too many errors with the old way...
https://uwgeodynamics.readthedocs.io/en/latest/UserGuide.html#passive-tracers

**Comment by BenedicteCT** [comment]
Still trying to re-define passive tracers and coordinates on a meshgrid
There seem to be a problem on the shape of centroids:
"TypeError: list indices must be integers or slices, not tuple"

**Comment by rbeucher** [comment]
Can you post the lines of code you are using?

**Comment by rbeucher** [comment]
Oh, I noticed that the docs did not get updated yet because we have not released 2.10...

```python
import UWGeodynamics as GEO
import numpy as np

 u = GEO.u
 Model = GEO.Model()
 cxpos = np.linspace(GEO.nd(20*u.kilometer), GEO.nd(40*u.kilometer),5)
 cypos = np.linspace(GEO.nd(20*u.kilometer), GEO.nd(40*u.kilometer),5)
 cxpos, cypos = np.meshgrid(cxpos, cypos)
 coords_centroid = np.ndarray((cxpos.size, 2))
 coords_centroid[:, 0] = cxpos.ravel()
 coords_centroid[:, 1] = cypos.ravel()
 
 coords = np.zeros((1, 2))
 tracers = Model.add_passive_tracers(vertices=coords,
                                      centroids=coords_centroid
```
That's how you define centroids

**Comment by BenedicteCT** [comment]
Yes indeed. that works ! thanks
PS: the model is starting properly as well with the added Model.materialField to the passive tracers
More in a few days after the full model has run

**Pull request merged**
