### PR TITLE
few doc strings

### PR DESCRIPTION
**Pull request by arijitlaik**
as always, wait for the weekend for more ;)

### CODE REVIEW

**Comment by rbeucher** [comment]
Can you go through the docstring and make sure they all roughly follow numpy style...?
Also I like your model example but I am not sure about the for loops. Would that make the model really harder to read if each material was done explicitly?

You can also add some explanation about the model. Maybe a link to your master thesis too. A short explanation of what the paper is about... 

I need to do that for the ormther examples too...

**Comment by rbeucher** [comment]
Also adds your name in the joss paper, your affiliation and orcid if you have one

**Comment by rbeucher** [comment]
Also if you feel brave... Can you add the reference of the rheology papers in the Json file? I did that for a couple of them

**Comment by arijitlaik** [comment]
Ya okay.
The loops can be done away with for the sake of simplicity, actually the looping is done to create a visual layering.
I can add a few more details on the model, but the paper has just been submitted and a similar but a bit complex model  is just a part of the paper. I want to keep the example simple I can add a bit of reference to other papers which kind of use a similar setup and pros and cons of that
Add my orchid and affiliation sure. Thanks :)
And I'll check the doc string and be brave :D to add refs to the rheologies

**Comment by rbeucher** [comment]
I am thinking of changing the name of the rheologies in the Viscous Registry.
Name of the authors is not good. 
Something starting with Dry_Olivine_paper_dislocation

What do you think

**Comment by RebeccaFarrington** [comment]
I like it!

**Comment by rbeucher** [comment]
I think it makes more sense... Now the question is, do I break backward compatibility? I would think yes... It's only going to be an issue for a few users...

**Comment by arijitlaik** [comment]
makes more sense. but at the cost of a few affected users

**Comment by arijitlaik** [comment]
I am mostly done with the viscous rheology file, hope you haven't done it yet, i'll complete the rest and send in a PR soon

**Comment by rbeucher** [comment]
I won't touch it. I just got rid of some ASCII character that were not recognised...

**Pull request merged**
